version: '2'
services:
    rimbomba-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/rimbomba/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=rimbomba
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
